name: Test SteamStore ETL on Multiple Platforms

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    environment:
      name: package-test

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.10, 3.11, 3.12]

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install SteamStore ETL Package
      run: |
        pip install steamstore-etl

    - name: Run tests
      run: |
        steamstore --help
        steamstore fetch_steamspy_metadata --max-pages 3

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Install the package
    #   run: |
    #     python -m pip install .

    # - name: Run tests
    #   run: |
    #     python -m pytest

#   build:
#     name: Build Package on Multiple Platforms
#     runs-on: ${{ matrix.os }}
    
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest]
#         python-version: [3.10, 3.11, 3.12]

#     steps:
#     - name: Check out the code
#       uses: actions/checkout@v4

#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install build

#     - name: Build the package
#       run: python -m build
